### PR TITLE
fix: set ALL as default for active profiles

### PR DESCRIPTION
**Pull request by pk-work**

### CODE REVIEW

**Comment by pk-work** [comment]
This could also be solved in Launcher line 49 by simply adding

```java
CLIConfigurator.inject(commandLine, options);
if (options.getActiveProfiles()) {
options.setActiveProfiles(Set.of(All);
```
But then NeonBeeOptions would only defaults to ALL when it is "generated" by Launcher.

**Comment by kristian** [comment]
There is no debate that imho that `ALL` should be the default, so line:

```java
private Set<NeonBeeProfile> activeProfiles = Set.of(NeonBeeProfile.ALL);
```

Is absolutely necessary. Question for me is: Is setting _no_ active profile (so purposefully calling `setActiveProfile()` a use case, or not? Does it make sense to set an empty profile, e.g. to only deploy system verticles? This way all other lines than the line above, would not require to be changed.

Also if they be changed, I don't think a change to the setter is necessary, because you do already check it it the getter, so I would suggest (if we decide to keep the logic) to change the getter to:

```java
return activeProfiles == null || activeProfiles.isEmpty() ? Set.of(NeonBeeProfile.ALL) : activeProfiles;
```

What do you think?

**Comment by pk-work** [comment]
Would be fine for me.

**Comment by kristian** [comment]
Ok, sounds good. Thanks @pk-work

**Comment by pk-work** [comment]
Just to double check:
 - We say the use case of an empty list of profiles is not required.
 - We say passing an empty list to setProfiles should have the same behavior than  passing `ALL`.

If this is fine we only need to change the line the getter to:
`return activeProfiles.isEmpty() ? Set.of(NeonBeeProfile.ALL) : activeProfiles;`

Because activeProfiles can't be null, if it is initialized with a Set.

**Comment by kristian** [comment]
No, I would say we should decide for either / or:

- Default should be ALL
- Can be overridden with an empty list, meaning no profiles

So I would only suggest to set the ALL profile as default

**Comment by pk-work** [comment]
This will not work, because the CLI in Launcher (when no profiles passed), will always call setActiveProfiles with an empty array which results in an empty List. So it will override the default value from the initialization.

Then we would need to change the Launcher to add the default value again, if no profiles argument is passed.

**Comment by kristian** [comment]
I did enable the `EnvironmentAwareCommandLine` to respect default options also for multi-valued options, see PR #106, this will also allow to set an empty list of active profiles. What do you think?

**Comment by kristian** [comment]
Fixed with PR#106

**Pull request closed without merging**
