### PR TITLE
fix: correct typos

### PR DESCRIPTION
**Pull request by gedack**
Fix some typos

### CODE REVIEW

**Review by s4heid — DISMISSED** [review]

**Comment by kristian** [comment]
Please wait to have this meged until the voter is fixed

I would not want to rebase my voter change to this one please, let's do it the other way around. Thanks!

**Comment by s4heid** [comment]
Thanks @gedack  for fixing those typos. Our voter is currently toast, but we're working on it.

**Comment by s4heid** [comment]
@gedack our voter is fixed, could you please rebase your change in order to get it merged? Thank you :)

**Comment by kristian** [comment]
lgtm, thanks @gedack

**Comment by kristian** [comment]
Please squash / rebase before merging. Thanks!

**Review by kristian — APPROVED** [review]

**Pull request closed without merging**
