### PR TITLE
fix: enable tests to run in intellij idea with coverage

### PR DESCRIPTION
**Pull request by gedack**
IntelliJ IDEA seems to inject a bunch of libraries to the classpath/classloader when running tests in coverage mode. This leads to issues when running tests where classpath scanning is involved, because for example classes like _org.jetbrains.coverage.org.objectweb.asm.ClassReader_ and _org.jetbrains.coverage.org.objectweb.asm.Opcodes_ (as well as many more) are found during the classpath scan even if they not match the lookup criteria.

Therefore the list of found files is filtered to clean it up from IntelliJ IDEA injected classes.

Steps to reproduce:
- open neonbee-core project in IntelliJ IDEA
- right click io.neonbee.internal.scanner.ClassPathScannerTest
- select "More Run/Debug" -> "Run 'ClassPathScannerTest' with Coverage
- see that the "scanForAnnotation" test is failing

Console output:
```
unexpected (2): org.jetbrains.coverage.org.objectweb.asm.Opcodes, org.jetbrains.coverage.org.objectweb.asm.ClassReader
---
expected      : [field.Hodor]
but was       : [org.jetbrains.coverage.org.objectweb.asm.Opcodes, field.Hodor, org.jetbrains.coverage.org.objectweb.asm.ClassReader]
java.lang.AssertionError: unexpected (2): org.jetbrains.coverage.org.objectweb.asm.Opcodes, org.jetbrains.coverage.org.objectweb.asm.ClassReader
---
expected      : [field.Hodor]
but was       : [org.jetbrains.coverage.org.objectweb.asm.Opcodes, field.Hodor, org.jetbrains.coverage.org.objectweb.asm.ClassReader]
	at io.vertx.junit5.VertxExtension.joinActiveTestContexts(VertxExtension.java:193)
	at io.vertx.junit5.VertxExtension.afterTestExecution(VertxExtension.java:164)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterTestExecutionCallbacks$9(TestMethodTestDescriptor.java:233)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:273)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:273)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:272)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterTestExecutionCallbacks(TestMethodTestDescriptor.java:232)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: unexpected (2): org.jetbrains.coverage.org.objectweb.asm.Opcodes, org.jetbrains.coverage.org.objectweb.asm.ClassReader
---
expected      : [field.Hodor]
but was       : [org.jetbrains.coverage.org.objectweb.asm.Opcodes, field.Hodor, org.jetbrains.coverage.org.objectweb.asm.ClassReader]
	at app//io.neonbee.internal.scanner.ClassPathScannerTest.lambda$futureContainsExactly$11(ClassPathScannerTest.java:151)
	at app//io.vertx.junit5.VertxTestContext.verify(VertxTestContext.java:368)
	at app//io.neonbee.internal.scanner.ClassPathScannerTest.lambda$futureContainsExactly$12(ClassPathScannerTest.java:150)
	at app//io.vertx.junit5.VertxTestContext.lambda$succeeding$2(VertxTestContext.java:215)
	at app//io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at app//io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at app//io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at app//io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at app//io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at app//io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at app//io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at app//io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at app//io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
```

### CODE REVIEW

**Comment by kristian** [comment]
Hey @gedack, thanks for updating the PR... I don't know if merging in the main branch will cause any problems?

As far as I understand you now created:

[your commit] ... [everything from main]

This is why it changed 14,253 additions and 5,832 deletions. Same goes for the other commit...

I think you rather have to:

checkout main
cherry pick [your commit]
then force push your change

This should give you the right order of commits :)

**Comment by gedack** [comment]
SORRY @kristian, I did not had my computer with an IDE and Git client, I only used the Web Browser and the editor there. Sorry for the inconvenience. I will update this later.

**Review by pk-work — DISMISSED** [review]

**Comment by pk-work** [comment]
As discussed, as soon as it is rebased I will merge it. That you don't have to rebase it a third time :)

**Comment by pk-work** [comment]
resolved by #125

**Pull request closed without merging**
